# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BikeTourPlanner
repository: ratrun/biketourplanner
tagline: An application for offline planning of bicycle tours. BikeTourPlanner is open source.
author :
  name : ratrun
  url : https://github.com/ratrun
  github : ratrun
description: > # this means to ignore newlines until "baseurl:"
 An application for offline planning of bicycle tours. BikeTourPlanner is OpenSource.
 BikeTourPlanner is an open source desktop application for offline planning of bicycle tours based on the GraphHopper routing engine.
 It allows the user to generate the routing data from OpenStreetMap data.
 It uses offline maps which are provided by OSM2VectorTiles.
baseurl: /BikeTourPlannerGHPages # the subpath of your site, e.g. /blog
github_username:  ratrun

# Build settings
markdown: kramdown
theme: jekyll-cayman-theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

